### ISSUE TITLE
Issues and warnings found while running run_recount_pump.sh

### ISSUE THREAD

**Issue by btrx-rkazi** [langmead-lab/monorail-external#1]
1. singularity/run_recount_pump.sh: 43: singularity/run_recount_pump.sh: [[: not found

2. prefetch --max-size 200G -L info -t http -O /container-mounts/recount/temp/dl-SRR390728 SRR3907282020-10-27T16:57:14 prefetch.2.9.1 info: KConfig(repository) found: using VResolver2020-10-27T16:57:39 prefetch.2.9.1 info: HTTP read failure: URL="  status=404; tried 1/6 times for 0 milliseconds total2020-10-27T16:57:39 prefetch.2.9.1 info: HTTP read failure: URL="  status=404; tried 2/6 times for 5 milliseconds total2020-10-27T16:57:39 prefetch.2.9.1 info: HTTP read failure: URL="  status=404; tried 3/6 times for 15 milliseconds total2020-10-27T16:57:39 prefetch.2.9.1 info: HTTP read failure: URL="  status=404; tried 4/6 times for 30 milliseconds total2020-10-27T16:57:39 prefetch.2.9.1 info: HTTP read failure: URL="  status=404; tried 5/6 times for 60 milliseconds total2020-10-27T16:57:39 prefetch.2.9.1 info: HTTP read failure: URL="  status=404; tried 6/6 times for 120 milliseconds total

3. 2020-10-27T16:57:40 fastq-dump.2.9.1 warn: column not found while opening table within short read archive module - column LABEL2020-10-27T16:57:40 fastq-dump.2.9.1 warn: column not found while opening table within short read archive module - column LABEL_START2020-10-27T16:57:40 fastq-dump.2.9.1 warn: column not found while opening table within short read archive module - column LABEL_LEN2020-10-27T16:57:40 fastq-dump.2.9.1 warn: column not found while opening table within short read archive module - column LABEL2020-10-27T16:57:40 fastq-dump.2.9.1 warn: column not found while opening table within short read archive module - column LABEL_START2020-10-27T16:57:40 fastq-dump.2.9.1 warn: column not found while opening table within short read archive module - column LABEL_LEN2020-10-27T16:57:40 fastq-dump.2.9.1 warn: column not found while opening table within short read archive module - column LABEL2020-10-27T16:57:40 fastq-dump.2.9.1 warn: column not found while opening table within short read archive module - column LABEL_START2020-10-27T16:57:40 fastq-dump.2.9.1 warn: column not found while opening table within short read archive module - column LABEL_LEN2020-10-27T16:57:40 fastq-dump.2.9.1 warn: column not found while opening table within short read archive module - column LABEL2020-10-27T16:57:40 fastq-dump.2.9.1 warn: column not found while opening table within short read archive module - column LABEL_START2020-10-27T16:57:40 fastq-dump.2.9.1 warn: column not found while opening table within short read archive module - column LABEL_LEN2020-10-27T16:57:40 fastq-dump.2.9.1 warn: column not found while opening table within short read archive module - column LABEL2020-10-27T16:57:40 fastq-dump.2.9.1 warn: column not found while opening table within short read archive module - column LABEL_START2020-10-27T16:57:40 fastq-dump.2.9.1 warn: column not found while opening table within short read archive module - column LABEL_LEN2020-10-27T16:57:40 fastq-dump.2.9.1 warn: column not found while opening table within short read archive module - column LABEL

**Comment by ChristopherWilks** [comment]
Just to loop back, I missed this when it was first posted.
The first one should be fixed at this point (working with this person's project offline).
The other two are specific to the SRA Toolkit's prefetch and fastq-dump, external tools the pump uses to get data from SRA.
While they can at times signal an issue with downloading data, it's not a pump problem per se.
