### ISSUE TITLE
Can't access files referenced in README.md

### ISSUE THREAD

**Issue by jgburk** [langmead-lab/monorail-external#16]
http://duffel.rail.bio/recount3/human/new_annotations/exon_sums/human.exon_sums.G026.gtf.gz and similar links referencing rail.bio appear to be broken at this time. Is there a mirror for these files?

To reproduce:

`$ wget http://duffel.rail.bio/recount3/human/new_annotations/exon_sums/human.exon_sums.G026.gtf.gz
--2022-05-09 08:11:13--  http://duffel.rail.bio/recount3/human/new_annotations/exon_sums/human.exon_sums.G026.gtf.gz
Resolving duffel.rail.bio (duffel.rail.bio)... failed: Name or service not known.
wget: unable to resolve host address ‘duffel.rail.bio’
`

**Comment by ChristopherWilks** [comment]
thanks for reporting, there was an administrative issue with the domain `duffel.rail.bio` which has been addressed
