### ISSUE TITLE
Recount unify step failing for the rule "split_fianl_rejoined_exons"

### ISSUE THREAD

**Issue by mayank-singh-sikarwar** [langmead-lab/monorail-external#19]
**Run command: /bin/bash /nfs/home/users/msikarwa/Documents/monorail-external/singularity/run_recount_unify.sh \
/nfs/home/users/msikarwa/Documents/singularity/recount-unify_1.1.0.sif \
hg38 \
/nfs/home/users/msikarwa/Documents/reference \
/nfs/home/users/msikarwa/Documents/run_3/unify_out \
/nfs/home/users/msikarwa/Documents/run_3/pump_out/output/ \
/nfs/home/users/msikarwa/Documents/input_data/sample_file.tsv \
6 \
SRP:237**

Step failed with the below error(small snap of the session, full logs are in the attachment):

[Mon Jul 11 14:45:19 2022]
rule split_final_rejoined_exons:
    input: all.exon_counts.rejoined.tsv.gz, all.exon_counts.rejoined.tsv.gz.accession_header
    output: exon_sums_per_study/37/SRP020237/mre.exon_sums.SRP020237.G026.gz, exon_sums_per_study/37/SRP020237/mre.exon_sums.SRP020237.G029.gz, exon_sums_per_study/37/SRP020237/mre.exon_sums.SRP020237.R109.gz, exon_sums_per_study/37/SRP020237/mre.exon_sums.SRP020237.F006.gz, exon_sums_per_study/37/SRP020237/mre.exon_sums.SRP020237.ERCC.gz, exon_sums_per_study/37/SRP020237/mre.exon_sums.SRP020237.SIRV.gz
    jobid: 19
    threads: 6

		/bin/bash /recount-unify/rejoin/split_out_exon_sums_by_study.sh mre G026,G029,R109,F006,ERCC,SIRV 1709834 /container-mounts/ref/exon_bitmasks.tsv /container-mounts/ref/exon_bitmask_coords.tsv all.exon_counts.rejoined.tsv.gz 6
        rm -rf exons_split_by_study_temp exon_annotation_split_runs
		
SRP020237	no_runs
ls: cannot access 'exons_split_by_study_temp/*.gz': No such file or directory
[Mon Jul 11 14:45:19 2022]
Error in rule split_final_rejoined_exons:
    jobid: 19
    output: exon_sums_per_study/37/SRP020237/mre.exon_sums.SRP020237.G026.gz, exon_sums_per_study/37/SRP020237/mre.exon_sums.SRP020237.G029.gz, exon_sums_per_study/37/SRP020237/mre.exon_sums.SRP020237.R109.gz, exon_sums_per_study/37/SRP020237/mre.exon_sums.SRP020237.F006.gz, exon_sums_per_study/37/SRP020237/mre.exon_sums.SRP020237.ERCC.gz, exon_sums_per_study/37/SRP020237/mre.exon_sums.SRP020237.SIRV.gz

RuleException:
CalledProcessError in line 333 of /recount-unify/Snakefile:
Command ' set -euo pipefail;  
		/bin/bash /recount-unify/rejoin/split_out_exon_sums_by_study.sh mre G026,G029,R109,F006,ERCC,SIRV 1709834 /container-mounts/ref/exon_bitmasks.tsv /container-mounts/ref/exon_bitmask_coords.tsv all.exon_counts.rejoined.tsv.gz 6
        rm -rf exons_split_by_study_temp exon_annotation_split_runs ' returned non-zero exit status 2.
  File "/recount-unify/Snakefile", line 333, in __rule_split_final_rejoined_exons
  File "/opt/conda/envs/recount-unify/lib/python3.9/concurrent/futures/thread.py", line 52, in run
Shutting down, this might take some time.
Exiting because a job execution failed. Look above for error message
Complete log: /container-mounts/working/.snakemake/log/2022-07-11T144342.634057.snakemake.log

**Comment: I am following all the instructions given in the readme docs and keeping each steps output separate to avoid any mix. I am using the latest image for both steps and latest fastQ files for this test run. However, I am not able to pinpoint why this error occurred. Please direct me how I can resolve this issue. Also, let me know if you need any other details from my side.**
[run_log.txt](https://github.com/langmead-lab/monorail-external/files/9084540/run_log.txt)
[monorail_commands.txt](https://github.com/langmead-lab/monorail-external/files/9084556/monorail_commands.txt)

**Comment by GauravR31** [comment]
Hello @mayank-singh-sikarwar I am facing the same issue, were you able to resolve this? If so, could you share how you did it?
