### ISSUE TITLE
"404: Not Found" error on `get_human_ref_indexes.sh`

### ISSUE THREAD

**Issue by lthiberiol** [langmead-lab/monorail-external#24]
The `404: Not Found` error is repeated for all files `get_human_ref_indexes.sh` try to download ( `salmon_index.tar.gz`, `unmapped_hisat2_idx.tar.gz`, `gtf.tar.gz`, and `fasta.tar.gz`). This also occurs when trying the `get_mouse_ref_indexes.sh` and `get_ce_ref_indexes.sh`.

```
--2023-05-23 11:57:29--  https://recount-ref.s3.amazonaws.com/hg38/star_idx.tar.gz
Resolving recount-ref.s3.amazonaws.com (recount-ref.s3.amazonaws.com)... 52.217.110.156, 52.217.236.201, 54.231.134.225, ...
Connecting to recount-ref.s3.amazonaws.com (recount-ref.s3.amazonaws.com)|52.217.110.156|:443... connected.
HTTP request sent, awaiting response... 404 Not Found
2023-05-23 11:57:29 ERROR 404: Not Found.

tar (child): star_idx.tar.gz: Cannot open: No such file or directory
tar (child): Error is not recoverable: exiting now
tar: Child returned status 2
tar: Error is not recoverable: exiting now
```

**Comment by BenLangmead** [comment]
Aha, yes, this is due to a recent move of those files into a public AWS bucket.  I will submit a fix for this in a moment and reply here when it's ready...

But I can tell you that the fix is to replace the prefix `https://recount-ref.s3.amazonaws.com/...` with the prefix `https://genome-idx.s3.amazonaws.com/recount/recount-ref/...`.

**Comment by BenLangmead** [comment]
I believe I have now fixed this with my latest commit: https://github.com/langmead-lab/monorail-external/commit/72c3b878e63772bc202096ce8837292a64ff1215

**Comment by rahulsimham** [comment]
Your new commit fixed the problem. Thanks!

**Comment by ChristopherWilks** [comment]
thanks Ben!
