### ISSUE TITLE
http://snaptron.cs.jhu.edu/data/temp/recount3test is not available

### ISSUE THREAD

**Issue by beeCwright** [langmead-lab/monorail-external#9]
I'm trying to test my recount3 installation in R as well as browse the directories at http://snaptron.cs.jhu.edu/data/temp/recount3test to learn how to structure the file hierarchy correctly but that URL is not returning a response.

I'm able to install recount3 and view the citation, but when I try and run the commands in R to fetch and run on sample data:

```
library(recount3)
recount3_cache_rm()
options(recount3_url = "http://snaptron.cs.jhu.edu/data/temp/recount3test")
hp<-available_projects()

Error: 'recount3_url' is not a valid supported URL since it's missing the URL/<organism>/homes_index text file or 'recount3_url' is not an existing directory in your file system.

```

Is that URL actually available? Or are those files hosted elsewhere?

**Comment by davemcg** [comment]
This was likely because snaptron was down temporarily due to maintenance. It works now.

**Comment by ChristopherWilks** [comment]
thanks @davemcg
